apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint
   namespace: dev
spec:
   type: NodePort
   selector:
     app: test
   ports:
      - port: 8888
        targetPort: 8888
        nodePort: 30002
