Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define "grvelvaS" do |control|
    control.vm.hostname = "grvelvaS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.name = "grvelvaS"
      v.memory = "4096"
      v.cpus = "1"
    end
  config.vm.provision "file", source: "scripts/", destination: "/tmp/"
  config.vm.provision "shell", inline: <<-SHELL
    chmod +x /tmp/scripts/start.sh
    /tmp/scripts/start.sh
  SHELL
  end
end
