# the base box
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/noble64"

  #vm configuration
  config.vm.define "ddiakovaS" do |control|
      control.vm.hostname = "ddiakovaS"
      control.vm.network "private_network", ip: "192.168.56.110"
      control.vm.synced_folder "./config", "/vagrant", type: "virtualbox"
      control.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "ddiakovaS"]
          v.memory = 2048
          v.cpus = 2
      end
      config.vm.provision "shell", inline: <<-SHELL
      SHELL
      control.vm.provision "shell", path: "scripts/server.sh"
    end
  
  config.vm.define "ddiakovaSW" do |work|
      work.vm.hostname = "ddiakovaSW"
      work.vm.network "private_network", ip: "192.168.56.111"
      work.vm.synced_folder "./config", "/vagrant", type: "virtualbox"
      work.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "ddiakovaSW"]
          v.memory = 2048
          v.cpus = 2
       end
       config.vm.provision "shell", inline: <<-SHELL
       SHELL
       work.vm.provision "shell", path: "scripts/agent.sh"
    end
  end
