apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  ports:
  - port: 3200
    targetPort: 8080
    protocol: TCP
  selector:
    app: app-one

---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  ports:
  - port: 3200
    targetPort: 8080
    protocol: TCP
  selector:
    app: app-two

---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  ports:
  - port: 3200
    targetPort: 8080
    protocol: TCP
  selector:
    app: app-three
